-- Gnuboard 5 호환 테이블
-- g5_board, g5_member, g5_write_* 등

SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

-- ============================================================
-- 게시판 설정 테이블 (g5_board)
-- ============================================================
CREATE TABLE IF NOT EXISTS `g5_board` (
  `bo_table` varchar(20) NOT NULL DEFAULT '' COMMENT '게시판 테이블명',
  `gr_id` varchar(255) NOT NULL DEFAULT '' COMMENT '게시판 그룹 ID',
  `bo_subject` varchar(255) NOT NULL DEFAULT '' COMMENT '게시판 제목',
  `bo_mobile_subject` varchar(255) NOT NULL DEFAULT '' COMMENT '모바일 제목',
  `bo_device` enum('both','pc','mobile') NOT NULL DEFAULT 'both' COMMENT '접근 기기',
  `bo_admin` varchar(255) NOT NULL DEFAULT '' COMMENT '게시판 관리자',
  `bo_list_level` tinyint(4) NOT NULL DEFAULT 1 COMMENT '목록 권한',
  `bo_read_level` tinyint(4) NOT NULL DEFAULT 1 COMMENT '읽기 권한',
  `bo_write_level` tinyint(4) NOT NULL DEFAULT 1 COMMENT '쓰기 권한',
  `bo_reply_level` tinyint(4) NOT NULL DEFAULT 1 COMMENT '답변 권한',
  `bo_comment_level` tinyint(4) NOT NULL DEFAULT 1 COMMENT '댓글 권한',
  `bo_html_level` tinyint(4) NOT NULL DEFAULT 1 COMMENT 'HTML 권한',
  `bo_link_level` tinyint(4) NOT NULL DEFAULT 1 COMMENT '링크 권한',
  `bo_upload_level` tinyint(4) NOT NULL DEFAULT 1 COMMENT '업로드 권한',
  `bo_download_level` tinyint(4) NOT NULL DEFAULT 1 COMMENT '다운로드 권한',
  `bo_use_category` tinyint(4) NOT NULL DEFAULT 0 COMMENT '카테고리 사용',
  `bo_category_list` text NOT NULL COMMENT '카테고리 목록',
  `bo_use_sideview` tinyint(4) NOT NULL DEFAULT 0 COMMENT '사이드뷰 사용',
  `bo_use_file_content` tinyint(4) NOT NULL DEFAULT 0 COMMENT '파일 내용 사용',
  `bo_use_secret` tinyint(4) NOT NULL DEFAULT 0 COMMENT '비밀글 사용',
  `bo_use_dhtml_editor` tinyint(4) NOT NULL DEFAULT 0 COMMENT 'DHTML 에디터 사용',
  `bo_use_rss_view` tinyint(4) NOT NULL DEFAULT 0 COMMENT 'RSS 사용',
  `bo_use_good` tinyint(4) NOT NULL DEFAULT 0 COMMENT '추천 사용',
  `bo_use_nogood` tinyint(4) NOT NULL DEFAULT 0 COMMENT '비추천 사용',
  `bo_use_name` tinyint(4) NOT NULL DEFAULT 0 COMMENT '이름 사용',
  `bo_use_signature` tinyint(4) NOT NULL DEFAULT 0 COMMENT '서명 사용',
  `bo_use_ip_view` tinyint(4) NOT NULL DEFAULT 0 COMMENT 'IP 표시',
  `bo_use_list_view` tinyint(4) NOT NULL DEFAULT 0 COMMENT '리스트뷰 사용',
  `bo_use_email` tinyint(4) NOT NULL DEFAULT 0 COMMENT '이메일 사용',
  `bo_use_cert` varchar(255) NOT NULL DEFAULT '' COMMENT '인증 사용',
  `bo_use_sns` tinyint(4) NOT NULL DEFAULT 0 COMMENT 'SNS 사용',
  `bo_use_captcha` tinyint(4) NOT NULL DEFAULT 0 COMMENT 'CAPTCHA 사용',
  `bo_sort_field` varchar(255) NOT NULL DEFAULT '' COMMENT '정렬 필드',
  `bo_page_rows` int(11) NOT NULL DEFAULT 15 COMMENT '페이지당 행 수',
  `bo_mobile_page_rows` int(11) NOT NULL DEFAULT 15 COMMENT '모바일 페이지당 행 수',
  `bo_subject_len` int(11) NOT NULL DEFAULT 60 COMMENT '제목 길이',
  `bo_mobile_subject_len` int(11) NOT NULL DEFAULT 30 COMMENT '모바일 제목 길이',
  `bo_new` int(11) NOT NULL DEFAULT 24 COMMENT '새글 시간',
  `bo_hot` int(11) NOT NULL DEFAULT 100 COMMENT '인기글 조회수',
  `bo_gallery_cols` int(11) NOT NULL DEFAULT 4 COMMENT '갤러리 컬럼 수',
  `bo_gallery_width` int(11) NOT NULL DEFAULT 202 COMMENT '갤러리 너비',
  `bo_gallery_height` int(11) NOT NULL DEFAULT 150 COMMENT '갤러리 높이',
  `bo_mobile_gallery_width` int(11) NOT NULL DEFAULT 125 COMMENT '모바일 갤러리 너비',
  `bo_mobile_gallery_height` int(11) NOT NULL DEFAULT 100 COMMENT '모바일 갤러리 높이',
  `bo_upload_size` bigint(20) unsigned NOT NULL DEFAULT 1048576 COMMENT '업로드 크기',
  `bo_reply_order` tinyint(4) NOT NULL DEFAULT 1 COMMENT '답변 순서',
  `bo_use_search` tinyint(4) NOT NULL DEFAULT 1 COMMENT '검색 사용',
  `bo_order` int(11) NOT NULL DEFAULT 0 COMMENT '게시판 순서',
  `bo_count_delete` int(11) NOT NULL DEFAULT 1 COMMENT '삭제 카운트',
  `bo_count_modify` int(11) NOT NULL DEFAULT 1 COMMENT '수정 카운트',
  `bo_read_point` int(11) NOT NULL DEFAULT 0 COMMENT '읽기 포인트',
  `bo_write_point` int(11) NOT NULL DEFAULT 0 COMMENT '쓰기 포인트',
  `bo_comment_point` int(11) NOT NULL DEFAULT 0 COMMENT '댓글 포인트',
  `bo_download_point` int(11) NOT NULL DEFAULT 0 COMMENT '다운로드 포인트',
  `bo_use_comment` tinyint(4) NOT NULL DEFAULT 1 COMMENT '댓글 사용',
  `bo_upload_count` tinyint(4) NOT NULL DEFAULT 2 COMMENT '업로드 개수',
  `bo_use_sns_comment` tinyint(4) NOT NULL DEFAULT 0 COMMENT 'SNS 댓글 사용',
  `bo_use_order` tinyint(4) NOT NULL DEFAULT 0 COMMENT '정렬 사용',
  `bo_notice` text NOT NULL COMMENT '공지사항',
  `bo_skin` varchar(255) NOT NULL DEFAULT 'basic' COMMENT '스킨',
  `bo_mobile_skin` varchar(255) NOT NULL DEFAULT 'basic' COMMENT '모바일 스킨',
  `bo_image_width` int(11) NOT NULL DEFAULT 835 COMMENT '이미지 너비',
  `bo_table_width` int(11) NOT NULL DEFAULT 100 COMMENT '테이블 너비',
  `bo_1` varchar(255) NOT NULL DEFAULT '' COMMENT '여분 필드1',
  `bo_2` varchar(255) NOT NULL DEFAULT '' COMMENT '여분 필드2',
  `bo_3` varchar(255) NOT NULL DEFAULT '' COMMENT '여분 필드3',
  `bo_4` varchar(255) NOT NULL DEFAULT '' COMMENT '여분 필드4',
  `bo_5` varchar(255) NOT NULL DEFAULT '' COMMENT '여분 필드5',
  `bo_6` varchar(255) NOT NULL DEFAULT '' COMMENT '여분 필드6',
  `bo_7` varchar(255) NOT NULL DEFAULT '' COMMENT '여분 필드7',
  `bo_8` varchar(255) NOT NULL DEFAULT '' COMMENT '여분 필드8',
  `bo_9` varchar(255) NOT NULL DEFAULT '' COMMENT '여분 필드9',
  `bo_10` varchar(255) NOT NULL DEFAULT '' COMMENT '여분 필드10',
  `bo_write_min` int(11) NOT NULL DEFAULT 0 COMMENT '최소 쓰기 포인트',
  `bo_write_max` int(11) NOT NULL DEFAULT 0 COMMENT '최대 쓰기 포인트',
  `bo_comment_min` int(11) NOT NULL DEFAULT 0 COMMENT '최소 댓글 포인트',
  `bo_comment_max` int(11) NOT NULL DEFAULT 0 COMMENT '최대 댓글 포인트',
  `bo_insert_content` text NOT NULL COMMENT '삽입 내용',
  `bo_gallery_list_use` tinyint(4) NOT NULL DEFAULT 0 COMMENT '갤러리 목록 사용',
  `bo_gallery_list_skin` varchar(255) NOT NULL DEFAULT '' COMMENT '갤러리 목록 스킨',
  `bo_use_list_file` tinyint(4) NOT NULL DEFAULT 0 COMMENT '목록 파일 사용',
  `bo_use_list_content` tinyint(4) NOT NULL DEFAULT 0 COMMENT '목록 내용 사용',
  `bo_use_email_cert` tinyint(4) NOT NULL DEFAULT 0 COMMENT '이메일 인증 사용',
  `bo_use_autosave` tinyint(4) NOT NULL DEFAULT 1 COMMENT '자동저장 사용',
  `bo_use_ip_block` tinyint(4) NOT NULL DEFAULT 0 COMMENT 'IP 차단 사용',
  `bo_count_write` int(11) NOT NULL DEFAULT 0 COMMENT '게시글 수',
  `bo_count_comment` int(11) NOT NULL DEFAULT 0 COMMENT '댓글 수',
  PRIMARY KEY (`bo_table`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='게시판 설정';

-- ============================================================
-- 회원 테이블 (g5_member)
-- ============================================================
CREATE TABLE IF NOT EXISTS `g5_member` (
  `mb_no` int(11) NOT NULL AUTO_INCREMENT COMMENT '회원 번호',
  `mb_id` varchar(20) NOT NULL DEFAULT '' COMMENT '회원 아이디',
  `mb_password` varchar(255) NOT NULL DEFAULT '' COMMENT '비밀번호',
  `mb_name` varchar(255) NOT NULL DEFAULT '' COMMENT '이름',
  `mb_nick` varchar(255) NOT NULL DEFAULT '' COMMENT '닉네임',
  `mb_nick_date` date NOT NULL DEFAULT '0000-00-00' COMMENT '닉네임 변경일',
  `mb_email` varchar(255) NOT NULL DEFAULT '' COMMENT '이메일',
  `mb_homepage` varchar(255) NOT NULL DEFAULT '' COMMENT '홈페이지',
  `mb_level` tinyint(4) NOT NULL DEFAULT 1 COMMENT '회원 레벨',
  `mb_sex` char(1) NOT NULL DEFAULT '' COMMENT '성별',
  `mb_birth` varchar(255) NOT NULL DEFAULT '' COMMENT '생년월일',
  `mb_tel` varchar(255) NOT NULL DEFAULT '' COMMENT '전화번호',
  `mb_hp` varchar(255) NOT NULL DEFAULT '' COMMENT '휴대폰',
  `mb_certify` varchar(20) NOT NULL DEFAULT '' COMMENT '본인인증',
  `mb_adult` tinyint(4) NOT NULL DEFAULT 0 COMMENT '성인인증',
  `mb_dupinfo` varchar(255) NOT NULL DEFAULT '' COMMENT '중복가입확인값',
  `mb_zip1` char(3) NOT NULL DEFAULT '' COMMENT '우편번호1',
  `mb_zip2` char(3) NOT NULL DEFAULT '' COMMENT '우편번호2',
  `mb_addr1` varchar(255) NOT NULL DEFAULT '' COMMENT '주소1',
  `mb_addr2` varchar(255) NOT NULL DEFAULT '' COMMENT '주소2',
  `mb_addr3` varchar(255) NOT NULL DEFAULT '' COMMENT '주소3',
  `mb_addr_jibeon` varchar(255) NOT NULL DEFAULT '' COMMENT '지번주소',
  `mb_signature` text NOT NULL COMMENT '서명',
  `mb_recommend` varchar(255) NOT NULL DEFAULT '' COMMENT '추천인',
  `mb_point` int(11) NOT NULL DEFAULT 0 COMMENT '포인트',
  `mb_today_login` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '오늘 로그인',
  `mb_login_ip` varchar(255) NOT NULL DEFAULT '' COMMENT '로그인 IP',
  `mb_datetime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '가입일시',
  `mb_ip` varchar(255) NOT NULL DEFAULT '' COMMENT '가입 IP',
  `mb_leave_date` varchar(8) NOT NULL DEFAULT '' COMMENT '탈퇴일',
  `mb_intercept_date` varchar(8) NOT NULL DEFAULT '' COMMENT '차단일',
  `mb_email_certify` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '이메일 인증일',
  `mb_email_certify2` varchar(255) NOT NULL DEFAULT '' COMMENT '이메일 인증키',
  `mb_memo` text NOT NULL COMMENT '메모',
  `mb_lost_certify` varchar(255) NOT NULL COMMENT '분실 인증',
  `mb_mailing` tinyint(4) NOT NULL DEFAULT 0 COMMENT '메일링 수신',
  `mb_sms` tinyint(4) NOT NULL DEFAULT 0 COMMENT 'SMS 수신',
  `mb_open` tinyint(4) NOT NULL DEFAULT 0 COMMENT '정보공개',
  `mb_open_date` date NOT NULL DEFAULT '0000-00-00' COMMENT '정보공개일',
  `mb_profile` text NOT NULL COMMENT '프로필',
  `mb_memo_call` varchar(255) NOT NULL DEFAULT '' COMMENT '메모 호출',
  `mb_1` varchar(255) NOT NULL DEFAULT '' COMMENT '여분 필드1',
  `mb_2` varchar(255) NOT NULL DEFAULT '' COMMENT '여분 필드2',
  `mb_3` varchar(255) NOT NULL DEFAULT '' COMMENT '여분 필드3',
  `mb_4` varchar(255) NOT NULL DEFAULT '' COMMENT '여분 필드4',
  `mb_5` varchar(255) NOT NULL DEFAULT '' COMMENT '여분 필드5',
  `mb_6` varchar(255) NOT NULL DEFAULT '' COMMENT '여분 필드6',
  `mb_7` varchar(255) NOT NULL DEFAULT '' COMMENT '여분 필드7',
  `mb_8` varchar(255) NOT NULL DEFAULT '' COMMENT '여분 필드8',
  `mb_9` varchar(255) NOT NULL DEFAULT '' COMMENT '여분 필드9',
  `mb_10` varchar(255) NOT NULL DEFAULT '' COMMENT '여분 필드10',
  PRIMARY KEY (`mb_no`),
  UNIQUE KEY `mb_id` (`mb_id`),
  KEY `mb_today_login` (`mb_today_login`),
  KEY `mb_datetime` (`mb_datetime`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='회원';
